version: "3.8"
services:
  dropbox_connector:
    build: .
    command: python main.py
    ports:
      - "8006:5000"
    depends_on:
      - redis
    volumes:
      - .:/python-flask
    env_file: 
      - .env
  
  redis:
    image: redis:alpine
    ports:
        - '6379:6379'