version: "3.8"
services:
  dropbox_connector:
    build: ./flask/
    command: ["python", "main.py"]
    ports:
      - "8006:5000"
    depends_on:
      - redis
    volumes:
      - ./flask:/python-flask
    env_file: 
      - ./flask/.env
  
  redis:
    build: ./redis/
    ports:
        - '6379:6379'